services:
  embr-ras-sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: embr-bot:simulation
    container_name: embr-ras-simulation
    hostname: embr-raspberrypi
    networks:
      - ros_net

    # Interactive terminal
    stdin_open: true
    tty: true
    
    # Environment variables
    environment:
      - ROS_DOMAIN_ID=0
    
    # Mount workspace for live development (optional)
    volumes:
      - ./ros2_ws:/workspace/ros2_ws:rw
      - ./Tools:/workspace/Tools:rw
    
    # Resource limits (simulating Raspberry Pi 4)
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 2G
    
    # Keep container running
    command: /bin/bash

  ember_robot_sim:
    build:
        context: ./LiDAR_Simulation
        dockerfile: Dockerfile
    container_name: ember_gz_sim
    image: gz_sim
    restart: "no"
    networks:
      - ros_net

    environment:
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_DOMAIN_ID=0

    working_dir: /home/ros/heatsim_ws
    user: ros
    stdin_open: true
    tty: true

    volumes:
      - ./LiDAR_Simulation/heatsim_ws:/home/ros/heatsim_ws:rw

    security_opt:
      - seccomp:unconfined

networks:
  ros_net:
    driver: bridge